export const UPDATE_MEALS = "UPDATE_MEALS";

export const ADD_TO_LIST = "ADD_TO_LIST";
export const ADD_MULTIPLE_TO_LIST = "ADD_MULTIPLE_TO_LIST";
export const REMOVE_FROM_LIST = "REMOVE_FROM_LIST";
export const CLEAR_LIST = "CLEAR_LIST";
export const UPDATE_LIST_QUANTITY = "UPDATE_LIST_QUANTITY";
export const TOGGLE_LIST = "TOGGLE_LIST";

export const UPDATE_MENUES = "UPDATE_MENUES";
export const UPDATE_CURRENT_MENU = "UPDATE_CURRENT_MENU";